const HasElectricity = {
    Yes: 'Yes',
    No: 'No',
    Maybe: 'Maybe',
};

const iconsMap = {
    Yes: 'favicon-green.ico',
    No: 'favicon-red.ico',
    Maybe: 'favicon-blue.ico',
    Success: 'favicon-green.ico',
    Failed: 'favicon-red.ico'
}

const periodColors = {
    Yes: 'green',
    No: 'red',
    Maybe: 'blue'
}

const periodMessages = {
    Yes: 'Has Electricity',
    No: 'No Electricity',
    Maybe: 'May turn OFF'
}

const PingState = {
    Success: 'Success',
    Failed: 'Failed'
};

const pingStateMessages = {
    Success: 'Has Electricity',
    Failed: 'No Electricity',
}

const pingStateColors = {
    Success: 'green',
    Failed: 'red',
}

const periodsData = {
    0: { // Sunday
        0: HasElectricity.No,
        1: HasElectricity.Maybe,
        2: HasElectricity.Maybe,
        3: HasElectricity.Maybe,
        4: HasElectricity.Maybe,
        5: HasElectricity.No,
        6: HasElectricity.No,
        7: HasElectricity.No,
        8: HasElectricity.No,
        9: HasElectricity.Yes,
        10: HasElectricity.Yes,
        11: HasElectricity.Yes,
        12: HasElectricity.Yes,
        13: HasElectricity.Maybe,
        14: HasElectricity.Maybe,
        15: HasElectricity.Maybe,
        16: HasElectricity.Maybe,
        17: HasElectricity.No,
        18: HasElectricity.No,
        19: HasElectricity.No,
        20: HasElectricity.No,
        21: HasElectricity.Yes,
        22: HasElectricity.Yes,
        23: HasElectricity.Yes,
    },
    1: { // Monday
        0: HasElectricity.Yes,
        1: HasElectricity.Maybe,
        2: HasElectricity.Maybe,
        3: HasElectricity.Maybe,
        4: HasElectricity.Maybe,
        5: HasElectricity.No,
        6: HasElectricity.No,
        7: HasElectricity.No,
        8: HasElectricity.No,
        9: HasElectricity.Yes,
        10: HasElectricity.Yes,
        11: HasElectricity.Yes,
        12: HasElectricity.Yes,
        13: HasElectricity.Maybe,
        14: HasElectricity.Maybe,
        15: HasElectricity.Maybe,
        16: HasElectricity.Maybe,
        17: HasElectricity.No,
        18: HasElectricity.No,
        19: HasElectricity.No,
        20: HasElectricity.No,
        21: HasElectricity.Yes,
        22: HasElectricity.Yes,
        23: HasElectricity.Yes,
    },
    2: { // Tuesday
        0: HasElectricity.Yes,
        1: HasElectricity.No,
        2: HasElectricity.No,
        3: HasElectricity.No,
        4: HasElectricity.No,
        5: HasElectricity.Yes,
        6: HasElectricity.Yes,
        7: HasElectricity.Yes,
        8: HasElectricity.Yes,
        9: HasElectricity.Maybe,
        10: HasElectricity.Maybe,
        11: HasElectricity.Maybe,
        12: HasElectricity.Maybe,
        13: HasElectricity.No,
        14: HasElectricity.No,
        15: HasElectricity.No,
        16: HasElectricity.No,
        17: HasElectricity.Yes,
        18: HasElectricity.Yes,
        19: HasElectricity.Yes,
        20: HasElectricity.Yes,
        21: HasElectricity.Maybe,
        22: HasElectricity.Maybe,
        23: HasElectricity.Maybe,
    },
    3: { // Wednesday
        0: HasElectricity.Maybe,
        1: HasElectricity.Yes,
        2: HasElectricity.Yes,
        3: HasElectricity.Yes,
        4: HasElectricity.Yes,
        5: HasElectricity.Maybe,
        6: HasElectricity.Maybe,
        7: HasElectricity.Maybe,
        8: HasElectricity.Maybe,
        9: HasElectricity.No,
        10: HasElectricity.No,
        11: HasElectricity.No,
        12: HasElectricity.No,
        13: HasElectricity.Yes,
        14: HasElectricity.Yes,
        15: HasElectricity.Yes,
        16: HasElectricity.Yes,
        17: HasElectricity.Maybe,
        18: HasElectricity.Maybe,
        19: HasElectricity.Maybe,
        20: HasElectricity.Maybe,
        21: HasElectricity.No,
        22: HasElectricity.No,
        23: HasElectricity.No,
    },
    4: { // Thursday
        0: HasElectricity.No,
        1: HasElectricity.Maybe,
        2: HasElectricity.Maybe,
        3: HasElectricity.Maybe,
        4: HasElectricity.Maybe,
        5: HasElectricity.No,
        6: HasElectricity.No,
        7: HasElectricity.No,
        8: HasElectricity.No,
        9: HasElectricity.Yes,
        10: HasElectricity.Yes,
        11: HasElectricity.Yes,
        12: HasElectricity.Yes,
        13: HasElectricity.Maybe,
        14: HasElectricity.Maybe,
        15: HasElectricity.Maybe,
        16: HasElectricity.Maybe,
        17: HasElectricity.No,
        18: HasElectricity.No,
        19: HasElectricity.No,
        20: HasElectricity.No,
        21: HasElectricity.Yes,
        22: HasElectricity.Yes,
        23: HasElectricity.Yes,
    },
    5: { // Friday
        0: HasElectricity.Yes,
        1: HasElectricity.No,
        2: HasElectricity.No,
        3: HasElectricity.No,
        4: HasElectricity.No,
        5: HasElectricity.Yes,
        6: HasElectricity.Yes,
        7: HasElectricity.Yes,
        8: HasElectricity.Yes,
        9: HasElectricity.Maybe,
        10: HasElectricity.Maybe,
        11: HasElectricity.Maybe,
        12: HasElectricity.Maybe,
        13: HasElectricity.No,
        14: HasElectricity.No,
        15: HasElectricity.No,
        16: HasElectricity.No,
        17: HasElectricity.Yes,
        18: HasElectricity.Yes,
        19: HasElectricity.Yes,
        20: HasElectricity.Yes,
        21: HasElectricity.Maybe,
        22: HasElectricity.Maybe,
        23: HasElectricity.Maybe,
    },
    6: { // Saturday
        0: HasElectricity.Maybe,
        1: HasElectricity.Yes,
        2: HasElectricity.Yes,
        3: HasElectricity.Yes,
        4: HasElectricity.Yes,
        5: HasElectricity.Maybe,
        6: HasElectricity.Maybe,
        7: HasElectricity.Maybe,
        8: HasElectricity.Maybe,
        9: HasElectricity.No,
        10: HasElectricity.No,
        11: HasElectricity.No,
        12: HasElectricity.No,
        13: HasElectricity.Yes,
        14: HasElectricity.Yes,
        15: HasElectricity.Yes,
        16: HasElectricity.Yes,
        17: HasElectricity.Maybe,
        18: HasElectricity.Maybe,
        19: HasElectricity.Maybe,
        20: HasElectricity.Maybe,
        21: HasElectricity.No,
        22: HasElectricity.No,
        23: HasElectricity.No,
    }
}
